baseURL = 'https://terminal.nickolaskraus.io'
languageCode = 'en-US'
title = 'Terminal'
theme = 'terminal'

[markup]
  [markup.highlight]
  # See: https://xyproto.github.io/splash/docs/
  style = 'gruvbox'
  [markup.goldmark]
    [markup.goldmark.extensions]
    taskList = false
    typographer = false
    [markup.goldmark.renderer]
    unsafe = true

# Google Analytics measurement ID (Google Analytics 4)
# [services]
#   [services.googleAnalytics]
#     id = 'G-MEASUREMENT_ID'

[params]
  [params.about]
  title = "Terminal"
  description = "A minimalist Hugo theme using Tailwind CSS and vanilla JavaScript."

  [params.seo]
    image = 'logo.png'
    twitter_card = 'summary'
    twitter_site = '@nickolashkraus'
    twitter_creator = '@nickolashkraus'

  [[params.socials]]
  icon = 'fa-brands fa-github'
  name = 'GitHub'
  url = 'https://github.com/nickolashkraus/terminal'

  [[params.socials]]
  icon = 'fa-solid fa-envelope'
  name = 'Email'
  url = 'mailto:0x@nickolaskraus.io'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 20

[[menus.aside]]
name = 'README.md'
pageRef = '/'
weight = 20

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
